rabinovichtv/urls.py
from django.conf.urls import patterns, include, url
from rabinovichtv import settings
from django.contrib import admin
from main.feed import LatestNewsFeed, LatestVideoFeed

from haystack.query import SearchQuerySet
from haystack.views import SearchView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'main.views.main', name='main'),
    url(r'^about', 'main.views.main', name='about'),
    url(r'^contacts', 'main.views.main', name='contacts'),

    #Photo news
    url(r'^photo/$', 'main.views.view_photo_news_all', name='view_photo_news_all'),

    #News
    url(r'^news/$', 'main.views.view_news_all', name='view_news_all'),
    url(r'^news/(?P<news_slug>[^\.]+).html', 'main.views.view_news', name='view_news'),

    #About and static
    url(r'^channel/about-us/$', 'main.views.main'),
    url(r'^channel/broadcasting/$', 'main.views.main'),
    url(r'^channel/news/$', 'main.views.main'),
    url(r'^channel/programs/$', 'main.views.main'),
    url(r'^channel/team/$', 'main.views.main'),
    url(r'^channel/feedback/$', 'main.views.feedback', name='feedback'),
    url(r'^channel/feedback/thankyou/$', 'main.views.feedback_thankyou', name='feedback_thankyou'),


    #Video
    url(r'^video/(?P<category_slug>[^\.]+)/(?P<video_slug>[^\.]+).html', 'main.views.view_video', name='view_video'),
    url(r'^video/(?P<category_slug>[^\.]+)/$', 'main.views.view_video_category', name='view_video_category'),
    url(r'^video/$', 'main.views.view_video_all', name='view_video_all'),

    #Poll
    url(r'^polls/(?P<poll_id>\d+)/vote/$', 'main.views.polls_vote', name='polls_vote'),
    url(r'^polls/(?P<poll_id>\d+)/result/$', 'main.views.polls_result', name='polls_result'),

    #RSS
    url(r'^rss/news/$', 'main.views.rss_news'),
    url(r'^rss/video/$', 'main.views.rss_video'),
    url(r'^feed/news$', LatestNewsFeed(), name='rss_news'),
    url(r'^feed/video$', LatestVideoFeed(), name='rss_videos'),

    url(r'^admin/', include(admin.site.urls)),

    (r'^tinymce/', include('tinymce.urls')),
    (r'^mce_filebrowser/', include('mce_filebrowser.urls')),


)


#Search
sqs = SearchQuerySet().order_by('-date')
urlpatterns = patterns('haystack.views',
    url(r'^search/$', SearchView(
        searchqueryset=sqs,
    )),
) +urlpatterns


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
) + urlpatterns

main/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from main.youtube import get_video_id

colors = (
    ('black', u'Обычный'),
    ('black_bold', u'Обычный жирный'),
    ('red', u'Красный'),
    ('red_bold', u'Красный жирный'),
    ('yellow', u'Желтый'),
    ('yellow_bold', u'Желтый жирный')
)


class Menu(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Заголовок')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"Меню"
        verbose_name_plural = u"Меню"



class MenuItem(models.Model):
    menu = models.ForeignKey(Menu)
    title = models.CharField(max_length=100, verbose_name=u'Заголовок')
    url = models.CharField(max_length=255, verbose_name=u'URL')
    is_active = models.BooleanField(default=True, verbose_name=u'Опубликована')
    #order = models.IntegerField(default=0, verbose_name=u'Порядок сортировки')
    position = models.PositiveSmallIntegerField(default=0, verbose_name=u'Порядок сортировки')

    class Meta:
        ordering = ('position',)
        verbose_name = u"Пункт меню"
        verbose_name_plural = u"Меню"



class StaticPage(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Заголовок')
    content = HTMLField(blank=True, verbose_name=u'Содержимое')
    template = models.FilePathField(path=settings.TEMPLATE_DIRS[0]+'/static/', verbose_name=u'Шаблон')
    slug = models.SlugField(max_length=100, verbose_name="URL", unique=True)
    is_active = models.BooleanField(default=True, verbose_name=u'Опубликована')

    class Meta:
        verbose_name = u"Статическая страница"
        verbose_name_plural = u"Статические страницы"

    def __unicode__(self):
        return self.title



class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Заголовок')
    #is_mainmenu = models.BooleanField(default=True, verbose_name=u'В главном меню')
    slug = models.SlugField(max_length=100, verbose_name="URL", unique=True)

    class Meta:
        verbose_name = u"Категория"
        verbose_name_plural = u"Категории"

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('view_video_category', (), {
            'category_slug': self.slug,
    })



class News(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'Заголовок')
    content = HTMLField(verbose_name=u'Содержимое')
    image = ImageField(max_length=255, blank=True, upload_to='news', verbose_name=u'Изображение')
    title_color = models.CharField(max_length=100, choices=colors, default='black', verbose_name=u'Цвет заголовка')
    is_photo = models.BooleanField(default=False, verbose_name=u'Фоторепортаж')
    views_count = models.IntegerField(default=0, verbose_name=u'Количество просмотров')
    slug = models.SlugField(max_length=100, verbose_name="URL", unique=True)
    is_main_page = models.BooleanField(default=False, verbose_name=u'На главной')
    is_active = models.BooleanField(default=True, verbose_name=u'Опубликована')
    date = models.DateTimeField(verbose_name=u'Дата публикации')

    class Meta:
        verbose_name = u"Новость"
        verbose_name_plural = u"Новости"

    def __unicode__(self):
        return self.title


    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True

    @models.permalink
    def get_absolute_url(self):
        return ('view_news', (), {
            'news_slug': self.slug,
    })


class NewsGalleryImage(models.Model):
    image = ImageField(upload_to="news_gallery", verbose_name=u'Изображение')
    title = models.CharField(max_length=300, blank=True, verbose_name=u'Заголовок')
    news = models.ForeignKey(News)

    def __unicode__(self):
        return self.title


    class Meta:
        verbose_name = u"Изображение"
        verbose_name_plural = u"Изображения галереи"

    def preview(self):
        if self.image:
            im = get_thumbnail(self.image, '100x100', crop='center')
            return '<img src="%s">' % im.url
        return ''

    preview.allow_tags = True



class Video(models.Model):
    title = models.CharField(max_length=200,verbose_name=u'Заголовок')
    category = models.ForeignKey(Category, related_name = 'category', verbose_name=u'Категория')
    content = HTMLField(blank=True, verbose_name=u'Описание')
    youtube_link = models.CharField(max_length=200, verbose_name=u"Ссылка на Youtube")
    views_count = models.IntegerField(default=0, verbose_name=u'Количество просмотров')
    date = models.DateTimeField(verbose_name=u'Дата публикации')
    is_main_page = models.BooleanField(default=False, verbose_name=u'На главной')
    is_active = models.BooleanField(default=True, verbose_name=u'Опубликовано')
    slug = models.SlugField(max_length=200, verbose_name="URL", unique=True)


    class Meta:
        verbose_name = u"Видеоролик"
        verbose_name_plural = u"Видеоролики"

    def __unicode__(self):
        return self.title

    def clean(self):
        # Check valid Youtube link
        if self.youtube_link:
            video_id = get_video_id(self.youtube_link)
            if not video_id:
                raise ValidationError(u'Проверьте правильность URL видеоролика!')


    def preview(self):
        if self.youtube_link:
            video_id = get_video_id(self.youtube_link)
            if video_id:
                return "<img src='http://img.youtube.com/vi/%s/2.jpg'/>" % video_id
            else:
                return ''
        return ''
    preview.allow_tags = True


    @models.permalink
    def get_absolute_url(self):
        return ('view_video', (), {
            'category_slug': self.category.slug,
            'video_slug': self.slug,
    })


class Survey(models.Model):
    title = models.CharField(max_length=200,verbose_name=u'Вопрос голосования')
    is_active = models.BooleanField(default=True, verbose_name=u'Активен')
    date = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата')

    class Meta:
        verbose_name = u"Опрос"
        verbose_name_plural = u"Опросы"

    def __unicode__(self):
        return self.title


class SurveyVariants(models.Model):
    title = models.CharField(max_length=200,verbose_name=u'Вариант ответа')
    count = models.IntegerField(default=0, verbose_name=u'Количество голосов')
    survey = models.ForeignKey(Survey)

    class Meta:
        verbose_name = u"Вариант ответа"
        verbose_name_plural = u"Варианты ответа"

    def __unicode__(self):
        return self.title


class Marquee(models.Model):
    title = models.CharField(max_length=400, verbose_name=u'Заголовок')
    is_active = models.BooleanField(default=True, verbose_name=u'Опубликовано')

    class Meta:
        verbose_name = u"Бегущая строка"
        verbose_name_plural = u"Бегущая строка"

    def __unicode__(self):
        return self.title



class Feedback(models.Model):
    title = models.CharField(max_length=200, verbose_name=u'Имя')
    email = models.EmailField(max_length=100, verbose_name=u'E-Mail')
    subject = models.CharField(max_length=400, blank=True, verbose_name=u'Тема')
    body = models.TextField(max_length=4000, verbose_name=u'Сообщение')
    date = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"Обратная связь"
        verbose_name_plural = u"Обратная связь"

templates/article.html
{% extends "base.html" %}
{% block title %}{{ article.title }}{% endblock %}
{% load thumbnail %}
{% load youtube_filter %}
{% block additional_css %}
    <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}style/section.article.css' />
    <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}style/lightbox.css' />
    <script type='text/javascript' src='{{ STATIC_URL }}js/lightbox.min.js'></script>
{% endblock %}

{% block content_left %}


    <div class="central_article_news">
        <div class="head"><h2><a class="caption" href="{% url "view_news_all" %}">Новости</a></h2></div>
        <div class="body">
            <div class="date"><span>{{ article.date|date:"d E Y" }}</span> Последнее обновление {{ article.date|date:"H:i" }}
                <div class="top_social_holder">
                    <noindex>
                        <div class="top_social_b">
                            <div class='g_button'><g:plusone size="medium"></g:plusone></div>
                            <div class='twitter_holder'>
                                <a href="javascript:void();" onclick="window.open('http://twitter.com/share?_=&count=none&original_referer=' + encodeURIComponent(document.location.href) + '&text=' + encodeURIComponent($('meta[property=\'og:title\']').attr('content')) + ' - ' +'&url=' + encodeURIComponent(document.location.href), 'Twitter', 'width=656,height=539,menubar=no,location=no,resizable=no,scrollbars=no,status=no');return false;"><img src=/static/img/buttons/twitter-top.png border=0></a>
                            </div>
                            <div class='fb_holder'>
                                <fb:like action="recommend" layout="button_count" show_faces="false" colorscheme="light" width="140" height="21"></fb:like>
                            </div>
                        </div>
                    </noindex>
                </div>
            </div>

            <!-- <div class='bleft'></div>-->
            <div class="bright">
                {% thumbnail article.image "315x210" crop="center" as im %}
                    <a href="{{ article.get_absolute_url }}" class="image " >
                        <img src="{{ im.url }}" alt="{{ n.name }}">
                    </a>
                {% endthumbnail %}
                <h1 class="title">{{ article.title }}</h1>
                {{ article.content|safe }}

                {% if article.newsgalleryimage_set.count > 0 %}
                    <h2>Фоторепортаж:</h2>
                    <div class="gallery">
                        {% for gallery_image in article.newsgalleryimage_set.all %}
                            <a href="{{MEDIA_URL}}{{gallery_image.image}}" data-lightbox="gallery" data-title="{{ gallery_image.title }}">
                                {% thumbnail gallery_image.image "145x80" crop="center" as im %}
                                    <img class="gallery-image" style="margin:0 auto" align="center" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                                {% endthumbnail %}
                            </a>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="clear"></div>



        <div class="bottom_social_holder">
            <noindex>
                <div class="social_links">
                    <div class='fb_holder'>
                        <fb:like action="recommend" show_faces="false" colorscheme="light" width="530" height="21"></fb:like>
                    </div>
                    <div class='g_button'><g:plusone size="medium"></g:plusone></div>
                    <div class='twitter_holder'>
                        <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
                    </div>
                    <div class="clear"></div>
                </div>
            </noindex>
        </div>


    </div>

{% endblock %}

templates/category.html
{% extends "base.html" %}
{% load thumbnail %}
{% load youtube_filter %}
{% block title %}{{ category.title }}{% endblock %}
{% block additional_css %}
    <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}style/section.video.css' />
{% endblock %}

{% block content_left %}



    <div class='central_main_box central_full_video_list' id='central_full_video_list'>

        <div class='head'>
            <h2><span class='caption'>{{ category.title }}</span></h2>

        </div>
        <div class='content'>

            {% for video_item in videos %}
                {% if forloop.first %}

                    <ul class='first_news_list'>

                        <li class='item '>
                            <a href='{{ video_item.get_absolute_url }}' class='link'>
                                <img class='image' src='{{ video_item.youtube_link|youthumbnail:'s' }}' alt='{{ video_item.title }}' />
           <span class='info'>
             <span class='title'>{{ video_item.title }}</span>
             <span class='descr'>{{ video_item.content|striptags|truncatechars:470 }}</span>
             <span class='date'>{{ video_item.date|date:"d E Y" }}</span>
           </span>
                                <span class='clear'></span>
                            </a>

                        </li>

                    </ul>
                    <div class='clear'></div>
                    <ul class='news_list'>
                {% else %}

                    <li class='item '>
                        <a href='{{ video_item.get_absolute_url }}' class='link'>
                            <img class='image' src='{{ video_item.youtube_link|youthumbnail:'s' }}' alt='{{ video_item.title }}' />
           <span class='info'>
             <span class='title'>{{ video_item.title }}</span>
             <span class='date'>{{ video_item.date|date:"d E Y" }}</span>
             <span class='descr'>{{ video_item.content|striptags|truncatechars:130 }}</span>
           </span>
                            <span class='clear'></span>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
            </ul>
            <div class='clear'></div>

            <div class="c_foot" style="">
                <div class="navigate">
                    {% if videos.has_previous %}
                        <span class="prev"><a href="?page={{ videos.previous_page_number }}">&lt;</a></span>
                    {% else %}
                        <span class="prev"></span>
                    {% endif %}

                    <div class="c_pager">
                        {% if videos.page_range_data.show_first %}
                            <a href="?page=1" class="page">1</a>
                            <span class="separator">...</span>
                        {% endif %}
                        {% for i in videos.page_range_data.page_range %}
                            {% ifequal i videos.number %}
                                <span class="selected">{{ i }}</span>
                            {% else %}
                                <a href="?page={{ i }}" class="page">{{ i }}</a>
                            {% endifequal %}
                        {% endfor %}
                        {% if videos.page_range_data.show_last %}
                            <span class="separator">...</span>
                            <a href="?page={{ videos.paginator.num_pages }}" class="page">{{ videos.paginator.num_pages }}</a>
                        {% endif %}
                    </div>

                    {% if videos.has_next  %}
                        <span class="next"><a href="?page={{ videos.next_page_number }}">&gt;</a></span>
                    {% else %}
                        <span class="next"></span>
                    {% endif %}
                </div>
            </div>


            <div class="clear"></div>
        </div>

    </div>

{% endblock %}

templates/feedback.html
{% extends "base.html" %}
{% block title %}Обратная связь{% endblock %}
{% block additional_css %}
    <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}style/section.article.css' />
{% endblock %}
{% block content_left %}
    <div class="central_article_news central_feedback_form">
        <div class="head"><h2><a class="caption" href="">О канале</a></h2></div>
        <div class="body">

            <ul class="menu">
                <li><a href="/channel/about-us/">О канале</a></li>
                <li><a href="/channel/broadcasting/">Вещание</a></li>
                <li><a href="/channel/news/">Новости</a></li>
                <li><a href="/channel/programs/">Программы</a></li>
                <li><a href="/channel/team/">Команда</a></li>
                <li class="active"><a class="active" href="/channel/feedback/">Обратная связь</a></li>
            </ul>
            <!-- <div class='bleft'></div>-->
            <div class="bright">
                <div class="aright">
                </div>
                <div class="clear"></div>
                <div id="central_feedback_form" class="holder_form">

                    <div class="contacts-form">
                        <form method="POST" class="ajax form ajax-ready">
                            {% csrf_token %}

                            <div class="fleft">
                                <label for="f1">Имя</label>
                            </div>
                            <div class="fright">
                                <input class="field" name="title" value="{{ form.data.title }}" id="f1" type="text">
                            </div>
                            <div class="fleft">
                                <label for="f2">E-mail</label>
                            </div>
                            <div class="fright">
                                <input class="field" name="email" value="{{ form.data.email }}" id="f2" type="text">
                            </div>
                            <div class="fleft">
                                <label for="f3">Тема</label>
                            </div>
                            <div class="fright">
                                <input class="field" name="subject" value="{{ form.data.subject }}" id="f3" type="text">
                            </div>
                            <div class="fleft">
                                <label for="f4" class="message">Сообщение</label>
                            </div>
                            <div class="fright">
                                <textarea name="body" class="message" id="f4">{{ form.data.body }}</textarea>
                                <span class="text "></span>
                                {% if form.errors %}
                                    <span class="text error">Проверьте правильно ли заполнены все поля</span>
                                {% endif %}
                            </div>
                            <div class="fleft">
                            </div>
                            <div class="fright btn_send">
                                <input class="btn_type_1" type="submit" value="Отослать">
                            </div>
                            <input name="action" value="sendmsg" type="hidden">
                        </form>
                    </div>


                </div>


            </div>
        </div>
    </div>
{% endblock %}

templates/feedback_thankyou.html
{% extends "base.html" %}
{% block title %}Обратная связь{% endblock %}
{% block additional_css %}
    <link rel='stylesheet' type='text/css' href='{{ STATIC_URL }}style/section.article.css' />
{% endblock %}
{% block content_left %}
<div class="central_article_news central_feedback_form">
  <div class="head"><h2><a class="caption" href="">О канале</a></h2></div>
  <div class="body">

    <ul class="menu">
      <li><a href="/channel/about-us/">О канале</a></li>
      <li><a href="/channel/broadcasting/">Вещание</a></li>
      <li><a href="/channel/news/">Новости</a></li>
      <li><a href="/channel/programs/">Программы</a></li>
      <li><a href="/channel/team/">Команда</a></li>
      <li class="active"><a class="active" href="/channel/feedback/">Обратная связь</a></li>
    </ul>
    <!-- <div class='bleft'></div>-->
    <div class="bright">
      <div class="aright">
      </div>
      <div class="clear"></div>
      <div id="central_feedback_form" class="holder_form"><div class="message"><span class="finish_message">Спасибо большое за Ваш отзыв.</span></div></div>


    </div>
  </div>



</div>
{% endblock %}

templates/header.html
<div id='header'>
    <div class='holder'>

        <div class='info'>
            <a href='{% url 'main' %}' class='logo_channel'>RabonivichTV</a>
            <div class='clear'></div>
        </div>


        <div class='right'>

            <div class='control_holder'>
<!--
                <div class='lang'>
                    <select id="select_lang" class="top_region">
                        <option value="1">English</option>
                        <option value="2" selected="selected">Русский</option>
                    </select>
                    <div class='clear'></div>
                </div>
-->
                <div class='search_holder'>
                    <div class='block_search'>
                        <form action='/search/'  method='get' name='menu_search' id='search' class='search'>
                            <div>
                                <label for='string' >Search</label>
                                <input type="text" name="q" id="query" value="{{ form.q.value }}" />
                                <input type='submit' value='Go' id='submit' />
                                <br class='clear' />
                            </div>
                        </form>
                    </div>
                </div>

                <div class='twitter_holder'><a href='https://twitter.com/RabinovichTV' target='_blank'><img border="0" src="{{STATIC_URL}}img/top_twitter.png"></a></div>
                <div class='fb_holder'><a href='https://www.facebook.com/Rabinovich.TV' target='_blank'><img border="0" src="{{STATIC_URL}}img/top_fb.png"></a></div>
                <div class='yt_holder'><a href='https://www.youtube.com/channel/UC9RgZLMErqwAlzXVgyhC3RQ/feed' target='_blank'><img border="0" src="{{STATIC_URL}}img/top_yt.png"></a></div>
                <div class='rss_holder'><a href='{% url "rss_news" %}' target='_blank'><img border="0" src="{{STATIC_URL}}img/top_rss.png"></a></div>

            </div>


            <ul class='menu js_hover'>

                {% for menu_item in menu %}
                    {% if forloop.first %}
                        <li class='item {% if menu_item.url == request.path %}selected{% endif %}'>

                            <a href='{{ menu_item.url }}' class='link' target='_self'>{{ menu_item.title }}</a>

                        </li>
                    {% else %}
                        <li class='item {% if menu_item.url in request.path %}selected{% endif %}'>

                            <a href='{{ menu_item.url }}' class='link' target='_self'>{{ menu_item.title }}</a>

                        </li>
                    {% endif %}
                {% endfor %}

            </ul>

            <div class='clear'></div>
            <!--//<a href='/' class='main_link'></a>//-->

        </div>
    </div>

</div>

templates/index.html
{% extends "base.html" %}
{% block title %}Главная{% endblock %}
{% load thumbnail %}
{% load youtube_filter %}
{% block content_top %}
    <div class='central_wide_ticker'>

        <div class='ticker_left'>

            <div class='bn_title'>Горячие новости</div>
            <ul class='bn_list'>
                {% for top_news_item in top_news %}
                    <li class='item_bn  {% cycle 'odd' 'even' %}'><a class='link' href='{{ top_news_item.get_absolute_url }}'>{{ top_news_item.title|truncatechars:35 }}</a></li>
                {% endfor %}
            </ul>
            <a class='btn_more' href='/news'>Все новости</a>

        </div>

        <div class='ticker_right'>
            <div class='player'>
                <div class='player vp' id='videoplayer'>

                <!--
                    <script type="text/javascript" src="http://media-player.cdn.level3.net/flash/v1_1_5/js/swfobject.js"></script>
                    <script type="text/javascript">
                        var flashvars = {};
                        flashvars.HaloColor = "0x0086db";
                        flashvars.ToolTips = "false";
                        flashvars.AutoPlay = "true";
                        flashvars.VolumeLevel = "50";
                        flashvars.CaptionURL = "";
                        flashvars.Title = "";
                        flashvars.Logo = "";
                        flashvars.SRC = "rtmp://jn1livefs.fplive.net/jn1live-live/_definst_/stream001RUS";
                        flashvars.BufferTime = "5";
                        flashvars.AutoHideControls = "false";
                        flashvars.IsLive = "false";
                        flashvars.hasPlaylist = "false";
                        flashvars.ShowPlaylist = "false";
                        flashvars.conviva_service_url = "";
                        flashvars.conviva_customer_id = "";
                        flashvars.conviva_assetname_prefix = "";
                        flashvars.isMobile = navigator.userAgent.toLowerCase().indexOf("android") > -1 ? "true" : "false";
                        var params = {};
                        params.wmode = "transparent";
                        params.allowfullscreen = "true";
                        var attributes = {};
                        attributes.id = "L3MP";
                        swfobject.embedSWF("http://media-player.cdn.level3.net/flash/v1_1_5/Level3MediaPlayer.swf", "altContent", "654", "360", "10.1.0", "http://media-player.cdn.level3.net/flash/v1_1_5/expressInstall.swf", flashvars, params, attributes);
                    </script>
                    -->
                    {% if top_video %}
                        {{ top_video.youtube_link|youtube_main_embed_url|safe }}
                    {% endif %}
                    <!--
                    <div id="altContent">
                        <a href="http://www.adobe.com/go/getflashplayer">
                            <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
                        </a>
                    </div>
                    -->

                </div>
            </div>
        </div>

    </div>
    <div class='clear'></div>
{% endblock %}


{% block content_left %}

    <div class='central_main_box central_main_last_video'>

        <div class='head'>
            <h2><span class='caption'>Последнее видео</span></h2>
            <div class='top_control'>
                <a class='btn_more' href='{% url "view_video_all" %}'>Все видео</a>
            </div>
        </div>
        <div class='content'>
            <ul class='video_list'>

                {% for last_videos_item in last_videos%}
                    <li class='item  first'>
                        <a href='{{ last_videos_item.get_absolute_url }}' class='link'>
                            <img class='image' src="{{ last_videos_item.youtube_link|youthumbnail:'s' }}" alt='' />
                   <span class='info'>
                    <span class='title'>{{ last_videos_item.title }}</span>
                    <span class='descr'>{{ last_videos_item.content|striptags|truncatechars:60 }}</span>
                    <span class='date'>{{ last_videos_item.date|date:"d E Y" }}</span>
                   </span>
                            <span class='clear'></span>
                        </a>

                    </li>
                {% endfor %}

            </ul>
            <div class='clear'></div>
        </div>

    </div>


{% endblock %}

templates/polls_vote.html
          <div class="poll_results">
            <ul class="res_answers">
             {% for poll_answer_item in choices %}
              <li class="item">
                <div class="text"><span>{{ poll_answer_item.title }}</span><strong>{{ poll_answer_item.percentage }}%</strong></div>
                <div class="graph"><div class="vote_part" style="width:{{ poll_answer_item.percentage }}%;"></div></div>
              </li>
             {% endfor %}
            </ul>
          </div>